"""Project-wide constants for the ETL pipeline."""

from __future__ import annotations

SUPPORTED_EXTENSIONS: dict[str, str] = {
    ".pdf": "pdf",
    ".docx": "docx",
    ".html": "html",
    ".htm": "html",
}

VALID_TOPICS: set[str] = {
    "machine_learning",
    "programming",
    "databases",
    "operating_systems",
    "computer_networks",
    "data_analysis",
    "mathematics",
    "unknown",
}

VALID_DIFFICULTIES: set[str] = {"easy", "medium", "hard"}

TOPIC_KEYWORDS: dict[str, tuple[str, ...]] = {
    "machine_learning": (
        "нейронная сеть",
        "градиентный спуск",
        "классификация",
        "регрессия",
        "обучение модели",
        "classification",
        "regression",
        "model",
        "training",
        "gradient descent",
        "neural network",
    ),
    "programming": (
        "алгоритм",
        "алгоритмы",
        "структура данных",
        "функция",
        "класс",
        "сортировка",
        "поиск",
        "хеширование",
        "очередь",
        "стек",
        "динамическое программирование",
        "автомат",
        "software engineering",
        "разработка по",
        "тестирование",
        "архитектура приложения",
        "python",
        "java",
        "programming",
        "algorithm",
        "algorithms",
        "sorting",
        "search",
        "hashing",
        "dynamic programming",
        "queue",
        "stack",
        "function",
        "class",
        "object",
    ),
    "databases": (
        "sql",
        "таблица",
        "индекс",
        "запрос",
        "postgresql",
        "транзакция",
        "big data",
        "большие данные",
        "etl",
        "data lake",
        "распределенное хранилище",
        "database",
        "index",
        "query",
        "transaction",
    ),
    "operating_systems": (
        "процесс",
        "поток",
        "память",
        "ядро",
        "операционная система",
        "process",
        "thread",
        "memory",
        "kernel",
        "operating system",
    ),
    "computer_networks": (
        "tcp",
        "ip",
        "маршрутизация",
        "протокол",
        "http",
        "dns",
        "информационная безопасность",
        "криптография",
        "шифрование",
        "аутентификация",
        "уязвимость",
        "information security",
        "cryptography",
        "encryption",
        "authentication",
        "vulnerability",
        "network",
        "routing",
        "protocol",
    ),
    "data_analysis": (
        "анализ данных",
        "визуализация",
        "pandas",
        "статистика",
        "data analysis",
        "dataset",
        "visualization",
        "statistics",
        "analytics",
        "big data",
        "большие данные",
        "spark",
        "hadoop",
        "airflow",
    ),
    "mathematics": (
        "матрица",
        "матрицы",
        "производная",
        "интеграл",
        "вероятность",
        "теорема",
        "доказательство",
        "граф",
        "дерево",
        "комбинаторика",
        "кратчайший путь",
        "поток",
        "паросочетание",
        "дискретная математика",
        "булева функция",
        "сложность",
        "matrix",
        "derivative",
        "integral",
        "probability",
        "theorem",
        "proof",
        "graph",
        "tree",
        "combinatorics",
        "shortest path",
        "matching",
    ),
}

STOP_WORDS: set[str] = {
    "and",
    "are",
    "for",
    "from",
    "have",
    "into",
    "not",
    "that",
    "the",
    "this",
    "with",
    "author",
    "prepared",
    "или",
    "как",
    "для",
    "над",
    "при",
    "это",
    "что",
    "чтобы",
    "который",
    "которая",
    "которые",
    "если",
    "также",
    "после",
    "будет",
    "может",
    "данных",
    "автор",
    "выполнил",
    "составитель",
}
